"""Stable local diagnostic codes, independent of the V3 wire contract."""

from enum import Enum


class MinerReason(str, Enum):
    NOT_SERVING = "not_serving"
    DISPATCH_FAILED = "dispatch_failed"
    RESPONSE_UNAVAILABLE = "response_unavailable"
    SLOT_MISMATCH = "slot_mismatch"
    ARTIFACT_INVALID = "artifact_invalid"
    TRAJECTORY_INVALID = "trajectory_invalid"
    PATCH_REJECTED = "patch_rejected"
    PATCH_STATIC_REJECTED = "patch_static_rejected"
    PATCH_APPLY_FAILED = "patch_apply_failed"
    SCRIPT_REJECTED = "script_rejected"
    WORKING_DIRECTORY_INVALID = "working_directory_invalid"
    SETUP_FAILED = "setup_failed"
    CHECK_FAILED = "check_failed"
    TIMEOUT = "timeout"
    MEMORY_LIMIT = "memory_limit"
    OUTPUT_LIMIT = "output_limit"
    RESULT_TREE_INVALID = "result_tree_invalid"


class RoundReason(str, Enum):
    LEASE_UNAVAILABLE = "lease_unavailable"
    UNSUPPORTED_PROFILE = "unsupported_profile"
    UNSUPPORTED_VERIFIER_POLICY = "unsupported_verifier_policy"
    INSUFFICIENT_STORAGE = "insufficient_storage"
    QUORUM_NOT_MET = "quorum_not_met"
    COMMIT_FAILED = "commit_failed"
    REVEAL_MISMATCH = "reveal_mismatch"
    GRADING_EXPIRED = "grading_expired"
    SUBMISSION_FORMAT_MISMATCH = "submission_format_mismatch"
    SUBMISSION_GRANT_MISMATCH = "submission_grant_mismatch"
    SUBMISSION_DOWNLOAD_FAILED = "submission_download_failed"
    UNSUPPORTED_TASK = "unsupported_task"
    WORKSPACE_INVALID = "workspace_invalid"
    PATCH_TOOL_FAILED = "patch_tool_failed"
    SETUP_UNAVAILABLE = "setup_unavailable"
    SCRIPT_UNAVAILABLE = "script_unavailable"
    VERIFIER_UNAVAILABLE = "verifier_unavailable"
    VALIDATOR_ERROR = "validator_error"
    WORKSPACE_DOWNLOAD_FAILED = "workspace_download_failed"
    WORKSPACE_EXTRACTION_FAILED = "workspace_extraction_failed"
    WORKSPACE_MATERIALIZATION_FAILED = "workspace_materialization_failed"
    VERIFIER_DOWNLOAD_FAILED = "verifier_download_failed"
    VERIFIER_INVALID = "verifier_invalid"
    CLEANUP_FAILED = "cleanup_failed"


class Stage(str, Enum):
    LEASE = "lease"
    WORKSPACE_DOWNLOAD = "workspace_download"
    WORKSPACE_EXTRACTION = "workspace_extraction"
    DISPATCH = "dispatch"
    COMMIT = "commit"
    VERIFIER_DOWNLOAD = "verifier_download"
    VERIFIER_EXTRACTION = "verifier_extraction"
    VERIFIER_MANIFEST = "verifier_manifest"
    SUBMISSION_DOWNLOAD = "submission_download"
    WORKSPACE_MATERIALIZATION = "workspace_materialization"
    GRADING = "grading"
    PATCH = "patch"
    SETUP = "setup"
    SCRIPT = "script"
    CHECK = "check"
    RESULT_TREE = "result_tree"
    CLEANUP = "cleanup"
